Add monkey-patch for wx.py.interpreter
C:/Python39/Lib/code.py:77:
    def runcode(self, code):
        try:
            exec(code, self.locals)
                     ^^^ missing globals()

Fix shell init globals

*   起動時のスクリプト実行エラー対処
    AttributeError: 'Interpreter' object has no attribute 'globals'