Fix Clipboard R/W functions
  * Fix Clipboard.imwrite img data
        change to more efficient way
        ++ change array.transpose --> array.repeat
        ++ change deprecated method tostring --> tobtyes
  * Fix Clipboard.imread for PY27 BUS:
        [C-v] read_buffer_from_clipboard:
        Clipboard.imread:
        PY2 Error:
        u"- No data in clipboard: 'memoryview' object has no attribute '__buffer__'"
        ++ change np.frombuffer --> np.asarray